# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pgm/workspace/opengl-dod

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/pgm/DATA/workspace/opengl-dod

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/pgm/DATA/workspace/opengl-dod/CMakeFiles /media/pgm/DATA/workspace/opengl-dod/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/pgm/DATA/workspace/opengl-dod/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named build/opengl-dod.out

# Build rule for target.
build/opengl-dod.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 build/opengl-dod.out
.PHONY : build/opengl-dod.out

# fast build rule for target.
build/opengl-dod.out/fast:
	$(MAKE) -f CMakeFiles/build/opengl-dod.out.dir/build.make CMakeFiles/build/opengl-dod.out.dir/build
.PHONY : build/opengl-dod.out/fast

src/IO.o: src/IO.cpp.o

.PHONY : src/IO.o

# target to build an object file
src/IO.cpp.o:
	$(MAKE) -f CMakeFiles/build/opengl-dod.out.dir/build.make CMakeFiles/build/opengl-dod.out.dir/src/IO.cpp.o
.PHONY : src/IO.cpp.o

src/IO.i: src/IO.cpp.i

.PHONY : src/IO.i

# target to preprocess a source file
src/IO.cpp.i:
	$(MAKE) -f CMakeFiles/build/opengl-dod.out.dir/build.make CMakeFiles/build/opengl-dod.out.dir/src/IO.cpp.i
.PHONY : src/IO.cpp.i

src/IO.s: src/IO.cpp.s

.PHONY : src/IO.s

# target to generate assembly for a file
src/IO.cpp.s:
	$(MAKE) -f CMakeFiles/build/opengl-dod.out.dir/build.make CMakeFiles/build/opengl-dod.out.dir/src/IO.cpp.s
.PHONY : src/IO.cpp.s

src/Log.o: src/Log.cpp.o

.PHONY : src/Log.o

# target to build an object file
src/Log.cpp.o:
	$(MAKE) -f CMakeFiles/build/opengl-dod.out.dir/build.make CMakeFiles/build/opengl-dod.out.dir/src/Log.cpp.o
.PHONY : src/Log.cpp.o

src/Log.i: src/Log.cpp.i

.PHONY : src/Log.i

# target to preprocess a source file
src/Log.cpp.i:
	$(MAKE) -f CMakeFiles/build/opengl-dod.out.dir/build.make CMakeFiles/build/opengl-dod.out.dir/src/Log.cpp.i
.PHONY : src/Log.cpp.i

src/Log.s: src/Log.cpp.s

.PHONY : src/Log.s

# target to generate assembly for a file
src/Log.cpp.s:
	$(MAKE) -f CMakeFiles/build/opengl-dod.out.dir/build.make CMakeFiles/build/opengl-dod.out.dir/src/Log.cpp.s
.PHONY : src/Log.cpp.s

src/Material.o: src/Material.cpp.o

.PHONY : src/Material.o

# target to build an object file
src/Material.cpp.o:
	$(MAKE) -f CMakeFiles/build/opengl-dod.out.dir/build.make CMakeFiles/build/opengl-dod.out.dir/src/Material.cpp.o
.PHONY : src/Material.cpp.o

src/Material.i: src/Material.cpp.i

.PHONY : src/Material.i

# target to preprocess a source file
src/Material.cpp.i:
	$(MAKE) -f CMakeFiles/build/opengl-dod.out.dir/build.make CMakeFiles/build/opengl-dod.out.dir/src/Material.cpp.i
.PHONY : src/Material.cpp.i

src/Material.s: src/Material.cpp.s

.PHONY : src/Material.s

# target to generate assembly for a file
src/Material.cpp.s:
	$(MAKE) -f CMakeFiles/build/opengl-dod.out.dir/build.make CMakeFiles/build/opengl-dod.out.dir/src/Material.cpp.s
.PHONY : src/Material.cpp.s

src/Renderer.o: src/Renderer.cpp.o

.PHONY : src/Renderer.o

# target to build an object file
src/Renderer.cpp.o:
	$(MAKE) -f CMakeFiles/build/opengl-dod.out.dir/build.make CMakeFiles/build/opengl-dod.out.dir/src/Renderer.cpp.o
.PHONY : src/Renderer.cpp.o

src/Renderer.i: src/Renderer.cpp.i

.PHONY : src/Renderer.i

# target to preprocess a source file
src/Renderer.cpp.i:
	$(MAKE) -f CMakeFiles/build/opengl-dod.out.dir/build.make CMakeFiles/build/opengl-dod.out.dir/src/Renderer.cpp.i
.PHONY : src/Renderer.cpp.i

src/Renderer.s: src/Renderer.cpp.s

.PHONY : src/Renderer.s

# target to generate assembly for a file
src/Renderer.cpp.s:
	$(MAKE) -f CMakeFiles/build/opengl-dod.out.dir/build.make CMakeFiles/build/opengl-dod.out.dir/src/Renderer.cpp.s
.PHONY : src/Renderer.cpp.s

src/Shader.o: src/Shader.cpp.o

.PHONY : src/Shader.o

# target to build an object file
src/Shader.cpp.o:
	$(MAKE) -f CMakeFiles/build/opengl-dod.out.dir/build.make CMakeFiles/build/opengl-dod.out.dir/src/Shader.cpp.o
.PHONY : src/Shader.cpp.o

src/Shader.i: src/Shader.cpp.i

.PHONY : src/Shader.i

# target to preprocess a source file
src/Shader.cpp.i:
	$(MAKE) -f CMakeFiles/build/opengl-dod.out.dir/build.make CMakeFiles/build/opengl-dod.out.dir/src/Shader.cpp.i
.PHONY : src/Shader.cpp.i

src/Shader.s: src/Shader.cpp.s

.PHONY : src/Shader.s

# target to generate assembly for a file
src/Shader.cpp.s:
	$(MAKE) -f CMakeFiles/build/opengl-dod.out.dir/build.make CMakeFiles/build/opengl-dod.out.dir/src/Shader.cpp.s
.PHONY : src/Shader.cpp.s

src/Transform.o: src/Transform.cpp.o

.PHONY : src/Transform.o

# target to build an object file
src/Transform.cpp.o:
	$(MAKE) -f CMakeFiles/build/opengl-dod.out.dir/build.make CMakeFiles/build/opengl-dod.out.dir/src/Transform.cpp.o
.PHONY : src/Transform.cpp.o

src/Transform.i: src/Transform.cpp.i

.PHONY : src/Transform.i

# target to preprocess a source file
src/Transform.cpp.i:
	$(MAKE) -f CMakeFiles/build/opengl-dod.out.dir/build.make CMakeFiles/build/opengl-dod.out.dir/src/Transform.cpp.i
.PHONY : src/Transform.cpp.i

src/Transform.s: src/Transform.cpp.s

.PHONY : src/Transform.s

# target to generate assembly for a file
src/Transform.cpp.s:
	$(MAKE) -f CMakeFiles/build/opengl-dod.out.dir/build.make CMakeFiles/build/opengl-dod.out.dir/src/Transform.cpp.s
.PHONY : src/Transform.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/build/opengl-dod.out.dir/build.make CMakeFiles/build/opengl-dod.out.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/build/opengl-dod.out.dir/build.make CMakeFiles/build/opengl-dod.out.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/build/opengl-dod.out.dir/build.make CMakeFiles/build/opengl-dod.out.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... build/opengl-dod.out"
	@echo "... edit_cache"
	@echo "... src/IO.o"
	@echo "... src/IO.i"
	@echo "... src/IO.s"
	@echo "... src/Log.o"
	@echo "... src/Log.i"
	@echo "... src/Log.s"
	@echo "... src/Material.o"
	@echo "... src/Material.i"
	@echo "... src/Material.s"
	@echo "... src/Renderer.o"
	@echo "... src/Renderer.i"
	@echo "... src/Renderer.s"
	@echo "... src/Shader.o"
	@echo "... src/Shader.i"
	@echo "... src/Shader.s"
	@echo "... src/Transform.o"
	@echo "... src/Transform.i"
	@echo "... src/Transform.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

